### ISSUE TITLE
initial list call cannot read path of undefined

### ISSUE THREAD

**Issue by seshu3564** [fkoester/angular-filemanager-nodejs-bridge#3]
i am using angular filemanger and this project as module in my own expressjs node project..
i setup everything but at the start of application which has angularfilemanager tag .  list Api is getting called  i am getting this error can someone help me!!

```
Creating a pool connected to localhost:28015
TypeError: Cannot read property 'path' of undefined
    at C:\Users\personal\fieldservice\node_modules\angular-filemanager-nodejs-bridge\routes\index.js:27:68
    at Layer.handle [as handle_request] (C:\Users\personal\fieldservice\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\personal\fieldservice\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\personal\fieldservice\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\personal\fieldservice\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\personal\fieldservice\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (C:\Users\personal\fieldservice\node_modules\body-parser\lib\types\urlencoded.js:82:7)
    at Layer.handle [as handle_request] (C:\Users\personal\fieldservice\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\personal\fieldservice\node_modules\express\lib\router\index.js:271:10)
    at C:\Users\personal\fieldservice\node_modules\body-parser\lib\read.js:129:5
```

**Comment by fkoester** [comment]
I am sorry, I am currently not working on this and I do not have the time to look into any issues with it.

Please either try to fix the problem yourself or check if someone else has solved it already.

**Comment by seshu3564** [comment]
ok i solved it!! all api calls are having called with different parametres and so i changed node apis myself!!

**Comment by bzvyagintsev** [comment]
Hi! How do you solve it? Can you give me a small instruction?

**Comment by seshu3564** [comment]
I have done it long back. So i even forgot what the error was about! And i am not currently working in that project. if you are facing any problem paste it here i will try to help. cheers!

**Comment by fkoester** [comment]
Pleasetry again with the latest changes by @bhargavkonkathi
